# fly.toml app configuration file generated for bdd-wizard on 2023-06-06T19:08:10+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bdd-wizard"
primary_region = "waw"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
